### ISSUE TITLE
インスタンス変数

### ISSUE THREAD

**Issue by c0a21149fe** [c0a2103365/ProjExD#11]
https://github.com/c0a2103365/ProjExD/blob/eb57d15a47736e8d7a1014bab4ca04a7bb0e9887/ex05/fight_kokaton.py#L85

せっかくクラスなので、wbとかを一応インスタンス変数にした方がいいかも

**Comment by c0a2103365** [comment]
wbが包含されているクラスはCommonfileクラスから継承しています。なので、wb等をインスタンス変数にすると、スーパークラスまで変更しなければならず、片方のCsvクラスにも影響を与えるため、変更はしません。
