### ISSUE TITLE
数値について

### ISSUE THREAD

**Issue by Ryo-Miyakawa** [c0a2103365/ProjExD#7]
https://github.com/c0a2103365/ProjExD/blob/daeba8cf8ba30c4a115dbde6185cad5b0210ebc9/ex03/maze.py#L48

同じ数値が使われているから、あらかじめ定義してもいいと思う。

**Comment by c0a2103365** [comment]
指摘していただいたIssueに関して、あらかじめ変数を定義すると、変数の意味が分かりにくくなり、複雑になってしまいます。よって、修正は致しません。
ご指摘ありがとうございます。
